### ISSUE TITLE
Access Violation

### ISSUE THREAD

**Issue by eltigre4jc** [jpmikkers/TFTPClient#1]
I have successfully used this client for transferring a bin file to a device. 
But when I tried for another model, from the same vendor, I got Access Violation.

`TFTPClient.Upload(New IPEndPoint(IPAddress.Parse("192.168.0.21"), 69), System.IO.Directory.GetCurrentDirectory() & "\" & path, "/tmp/temp/fw_1200.bin")`

Why am I getting this error? it maybe something with the server?

**Comment by jpmikkers** [comment]
Hi,
If you copy-paste the exception + stack-trace that occurred, that'll show if the error happened on the client or server.

**Comment by eltigre4jc** [comment]
Server Error Access Violation: Access Violation
   at CodePlex.JPMikkers.TFTP.Client.TFTPClient.HandleError(TFTPPacket_Error p) in c:\Users\z003mh7c\Downloads\TFTPClient-master\TFTPClient\Library\TFTPClient.cs:line 504
   at CodePlex.JPMikkers.TFTP.Client.TFTPClient.DoUpload(TFTPPacket packet) in c:\Users\z003mh7c\Downloads\TFTPClient-master\TFTPClient\Library\TFTPClient.cs:line 425
   at CodePlex.JPMikkers.TFTP.Client.TFTPClient.FilterPacket(TFTPPacket packet, Func`2 step) in c:\Users\z003mh7c\Downloads\TFTPClient-master\TFTPClient\Library\TFTPClient.cs:line 222
   at CodePlex.JPMikkers.TFTP.Client.TFTPClient.<Upload>b__38_0(TFTPPacket p) in c:\Users\z003mh7c\Downloads\TFTPClient-master\TFTPClient\Library\TFTPClient.cs:line 310
   at CodePlex.JPMikkers.TFTP.Client.TFTPClient.PumpPackets(Func`2 step) in c:\Users\z003mh7c\Downloads\TFTPClient-master\TFTPClient\Library\TFTPClient.cs:line 164
   at CodePlex.JPMikkers.TFTP.Client.TFTPClient.Upload(String filename, Stream stream) in c:\Users\z003mh7c\Downloads\TFTPClient-master\TFTPClient\Library\TFTPClient.cs:line 310
   at CodePlex.JPMikkers.TFTP.Client.TFTPClient.Upload(IPEndPoint serverEndPoint, Stream localStream, String remoteFilename, Settings settings) in c:\Users\z003mh7c\Downloads\TFTPClient-master\TFTPClient\Library\TFTPClient.cs:line 542
   at CodePlex.JPMikkers.TFTP.Client.TFTPClient.Upload(IPEndPoint serverEndPoint, String localFilename, String remoteFilename, Settings settings) in c:\Users\z003mh7c\Downloads\TFTPClient-master\TFTPClient\Library\TFTPClient.cs:line 534
   at SiwarexTest.WP2XXObject.PerformFirmwareUpdateAndRestartDevice(String path, Boolean waitForEth, Int32 waitAfterRestart)

**Comment by jpmikkers** [comment]
Right, this is TFTP error code 2, sent by the server. It means you don't have write permissions in the directory you're trying to upload to.
